# These formatting rules to try conform the Substrate style guidelines:
# >   https://wiki.parity.io/Substrate-Style-Guide

comment_width = 80
wrap_comments = true

reorder_imports = true
hard_tabs = true
max_width = 120

license_template_path = "LICENSE_TEMPLATE"
